from . import equipment
from . import area
from . import type_of_operation
from . import business
from . import res_users
from . import hr_department
from . import hr_employee
from . import purchase_order
from . import account_move
from . import account_asset
